### ISSUE TITLE
Default branch ?

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-authentication-service#12]
Let's see which one is default branch here, seem to be a mess

**Comment by pinclau** [comment]
Default branch seems to be 2.0 as 2.1 is behind 2.0 with commits

**Comment by arhimede** [comment]
Probably 2.1 was a dead end.
Please create a 2.9 branch

**Comment by arhimede** [comment]
@cPintiuta Please use the branch:   **2.9-PHP-8.1**
which is now the default one

**Comment by pinclau** [comment]
@arhimede i made a release from 2.9-PHP-8.1, you will need to make the default branch this one and close this issue after

**Comment by arhimede** [comment]
done
